-- +goose Up
CREATE TABLE posts(
id BIGINT  GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
title TEXT NOT NULL,
content TEXT NOT NULL,
created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP

);
CREATE INDEX idx_posts_user_id ON posts(user_id)

-- +goose Down
DROP TABLE posts;
